### ISSUE TITLE
decimali troncati

### ISSUE THREAD

**Issue by piersoft** [openfuffa/soldipubblici#2]
tutti i valori estratti, sono da dividere per 100 in quanto manca la virgola decimale.

esempio 12345,67 diventa 1234567 e quindi i valori sono tutti sfasati

**Comment by grigio** [comment]
A cosa ti riferisci in particolare? I dati estratti con questo sistema sono "grezzi" ovvero così come sono o erano salvati nel json originale. Probabilmente facevano la divisione a livello applicativo

**Comment by piersoft** [comment]
Mhm forse si. A questo punto va fatto a posteriori, anche se non sarà semplice
